[package]
name = "space_editor"
version = "0.2.2"
edition = "2021"
default-run = "space_editor"
license = "MIT OR Apache-2.0"
keywords = ["gamedev", "editor", "bevy"]
categories = ["game-development"]
exclude = ["/assets", "/examples"]
description = "Prefab editor for bevy game engine. Make levels/object templates with intuitive UI"
readme = "README.md"
homepage = "https://github.com/rewin123/space_editor"
repository = "https://github.com/rewin123/space_editor"

[dependencies]
bevy = "0.12"
bevy_egui = "0.23"
egui-gizmo = "0.12"
bevy-scene-hook = "9"
ron = "0.8"
serde = "1"
bevy_panorbit_camera = "0.9"
bevy-inspector-egui = {version = "0.21", features = ["bevy_pbr", "highlight_changes"]}
pretty-type-name = "1.0"
bevy_mod_picking = {version = "0.17", default-features = false, features = ["backend_raycast", "selection"]}
bevy_debug_grid = "0.3"
egui_dock = "0.8"
egui_file = "0.11"

bevy_xpbd_3d = {version="0.3", default-features = false, optional = true}

[profile.dev.package.bevy_xpbd_3d]
opt-level = 3

[features]
bevy_xpbd_3d = ["dep:bevy_xpbd_3d", "bevy_xpbd_3d/debug-plugin", "bevy_xpbd_3d/3d", "bevy_xpbd_3d/collider-from-mesh", "bevy_xpbd_3d/f32"]
persistance_editor = []

[[example]]
name = "platformer"
required-features = ["bevy_xpbd_3d"]


[[example]]
name = "spawn_prefab_with_physics"
required-features = ["bevy_xpbd_3d"]