[package]
name = "space_editor"
version.workspace = true 
edition.workspace = true 
license.workspace = true 
authors.workspace = true 
keywords.workspace = true 
categories.workspace = true 
exclude = ["/assets", "/examples"]
description = "Prefab editor for bevy game engine. Make levels/object templates with intuitive UI"
readme = "README.md"
homepage = "https://github.com/rewin123/space_editor"
repository = "https://github.com/rewin123/space_editor"

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["rewin <rewin1996@gmail.com>"]
keywords = ["gamedev", "editor", "bevy"]
categories = ["game-development"]

[workspace.dependencies]
bevy = "0.12"

# Editor Crates
space_prefab = { version = "*", path = "crates/prefab" }
space_shared = { version = "*", path = "crates/shared" }
space_undo = { version = "*", path = "crates/undo" }
space_persistence = { version = "*", path = "crates/persistence"}
space_editor_core = { version = "*", path = "crates/editor_core", features = ["persistence_editor"] }
space_editor_ui = { version = "*", path = "crates/editor_ui", features = ["persistence_editor"] }
ron = "0.8"
serde = "1"

space_bevy_xpbd_plugin = { version = "*", path = "modules/bevy_xpbd_plugin"}

[dependencies]
bevy.workspace = true
space_editor_ui = {workspace = true, version = "*" }
space_prefab = {workspace = true, version = "*" }

# Modules for external crates
space_bevy_xpbd_plugin = {version = "*", workspace = true, optional = true }


# For versions 1.74+
[lints.rust]
future-incompatible = "warn"
nonstandard_style = "deny"
# Remove once fully deprecated
type_complexity = { level = "allow", priority = 2 }

[lints.clippy]
nursery = { level = "deny", priority = 0 }
all = { level = "deny", priority = 1 }
# Bevy Related
cognitive_complexity = { level = "allow", priority = 2 }
needless_pass_by_ref_mut = { level = "allow", priority = 2 }
significant_drop_in_scrutinee = { level = "allow", priority = 2 }
significant_drop_tightening = { level = "allow", priority = 2 }
type_complexity = { level = "allow", priority = 2 }
too_many_arguments = { level = "allow", priority = 2 }

[profile.dev.package.bevy_xpbd_3d]
opt-level = 3

[features]
bevy_xpbd_3d = ["dep:space_bevy_xpbd_plugin"]
persistence_editor = []
editor = []
default = ["bevy_xpbd_3d", "persistence_editor", "editor"]

[[example]]
name = "platformer"
required-features = ["bevy_xpbd_3d"]


[[example]]
name = "spawn_prefab_with_physics"
required-features = ["bevy_xpbd_3d"]