[package]
name = "space_editor"
version = "0.1.0"
edition = "2021"
default-run = "space_editor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
bevy_egui = "0.21"
egui-gizmo = "0.11.0"
bevy-scene-hook = "7"
ron = "0.8.0"
bevy_panorbit_camera = "0.7.0"
bevy-inspector-egui = {version = "0.19.0", features = ["bevy_pbr", "highlight_changes"]}
