[package]
name = "prefab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy.workspace = true
ron.workspace = true
serde.workspace = true
shared.workspace = true
undo.workspace = true

bevy-scene-hook = "9"
bevy-inspector-egui = { version = "0.21", features = ["bevy_pbr", "highlight_changes"]}
