[package]
name = "persistence"
version.workspace = true 
edition.workspace = true 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy.workspace = true
ron.workspace = true 
serde.workspace = true