[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy.workspace = true


bevy-inspector-egui = { version = "0.21", features = ["bevy_pbr", "highlight_changes"]}
egui_file = "0.11"